import type { AnalysisResult } from './types'

export const DEMO_RESULT: AnalysisResult = {
  job_id: 'static-demo',
  source_name: 'movie-ad-ai-demo.mp4',
  duration_seconds: 70.022,
  media_url: '/media/demo/movie-ad-ai-demo.mp4',
  generated_at: '2026-09-26T13:21:22.211572Z',
  summary: {
    scene_count: 5,
    candidate_count: 4,
    safe_candidate_count: 4,
    break_count: 1,
    ad_load_percent: 7.892,
  },
  policy: {
    max_breaks_per_hour: 4,
    min_gap_seconds: 420,
    max_ad_load_percent: 8,
    min_interruptibility: 0.62,
  },
  models: {
    visual: 'FFmpeg + transcript fallback',
    speech: 'timed subtitle track',
    semantics: 'lexical fail-closed fallback',
    degraded: true,
    notes: ['Static Space serves a verified CPU analysis snapshot'],
  },
  scenes: [
    {
      id: 'scene-0001',
      start: 0,
      end: 14.021,
      duration: 14.021,
      visual_score: 0,
      dominant_activity: 'travel',
      activities: ['travel'],
      contexts: ['travel', 'family'],
      mood: 'calm',
      description: 'A calm train journey home.',
      transcript: 'A calm train journey home.',
    },
    {
      id: 'scene-0002',
      start: 14.021,
      end: 28.021,
      duration: 14,
      visual_score: 1,
      dominant_activity: 'family',
      activities: ['family'],
      contexts: ['family'],
      mood: 'calm',
      description: 'A joyful family reunion at home.',
      transcript: 'A joyful family reunion at home.',
    },
    {
      id: 'scene-0003',
      start: 28.021,
      end: 42.021,
      duration: 14,
      visual_score: 1,
      dominant_activity: 'cooking',
      activities: ['cooking'],
      contexts: ['cooking'],
      mood: 'calm',
      description: 'Friends cook dinner together in the kitchen.',
      transcript: 'Friends cook dinner together in the kitchen.',
    },
    {
      id: 'scene-0004',
      start: 42.021,
      end: 56.021,
      duration: 14,
      visual_score: 1,
      dominant_activity: 'family',
      activities: ['family'],
      contexts: ['funeral', 'family'],
      mood: 'somber',
      description: 'A family mourns quietly after a funeral.',
      transcript: 'A family mourns quietly after a funeral.',
    },
    {
      id: 'scene-0005',
      start: 56.021,
      end: 70.022,
      duration: 14.001,
      visual_score: 1,
      dominant_activity: 'stargazing',
      activities: ['stargazing'],
      contexts: ['stargazing'],
      mood: 'calm',
      description: 'Friends are stargazing under the night sky.',
      transcript: 'Friends are stargazing under the night sky.',
    },
  ],
  candidates: [
    {
      id: 'boundary-14021',
      timestamp: 14.021,
      interruptibility_score: 0.9455,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '1.20s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 1, silence_seconds: 1.2, semantic_shift: 0.7273, speech_overlap: false, edge_margin: 14.021 },
    },
    {
      id: 'boundary-28021',
      timestamp: 28.021,
      interruptibility_score: 0.965,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '1.20s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 1, silence_seconds: 1.2, semantic_shift: 0.8248, speech_overlap: false, edge_margin: 28.021 },
    },
    {
      id: 'boundary-42021',
      timestamp: 42.021,
      interruptibility_score: 0.9605,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '1.20s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 1, silence_seconds: 1.201, semantic_shift: 0.8024, speech_overlap: false, edge_margin: 28.001 },
    },
    {
      id: 'boundary-56021',
      timestamp: 56.021,
      interruptibility_score: 0.9595,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '1.20s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 1, silence_seconds: 1.2, semantic_shift: 0.7974, speech_overlap: false, edge_margin: 14.001 },
    },
  ],
  breaks: [
    {
      id: 'break-01',
      timestamp: 28.021,
      time_offset: '00:00:28.021',
      score: 0.965,
      scene_id: 'scene-0003',
      brand: {
        id: 'rannabondhu',
        name: 'RannaBondhu',
        category: 'meal kits',
        tagline: 'Good evenings begin in the kitchen.',
        color: '#D94A3D',
      },
      creative_url: '/media/ads/rannabondhu.mp4',
      duration: 6,
      match_score: 1,
      why: [
        "dominant activity 'cooking' match 100%",
        'supporting activity match 100%',
        'positive context match 100%',
        'safe transition from scene-0002 to scene-0003',
      ],
      blocked_brands: [],
    },
  ],
  manifest_url: '',
  debug_url: '',
}