import sceneData from '../../data/demo/mohanagar.scenes.json'
import type { AnalysisResult, Scene } from './types'

const scenes: Scene[] = sceneData.map((scene, index) => ({
  id: `scene-${String(index + 1).padStart(4, '0')}`,
  start: scene.start,
  end: scene.end,
  duration: Number((scene.end - scene.start).toFixed(3)),
  visual_score: index === 0 ? 0 : 1,
  dominant_activity: scene.dominant_activity,
  activities: scene.activities,
  contexts: scene.contexts,
  mood: scene.mood,
  description: scene.description,
  transcript: scene.description,
}))

export const DEMO_RESULT: AnalysisResult = {
  job_id: 'static-demo',
  source_name: 'mohanagar.mp4',
  duration_seconds: 1396.63,
  media_url: '/media/demo/mohanagar.mp4',
  generated_at: '2026-09-26T13:21:22.211572Z',
  summary: {
    scene_count: 9,
    candidate_count: 6,
    safe_candidate_count: 6,
    break_count: 1,
    ad_load_percent: 0.43,
  },
  policy: {
    max_breaks_per_hour: 4,
    min_gap_seconds: 420,
    max_ad_load_percent: 8,
    min_interruptibility: 0.62,
  },
  models: {
    visual: 'FFmpeg + transcript fallback',
    speech: 'timed subtitle track',
    semantics: 'lexical fail-closed fallback',
    degraded: true,
    notes: ['Static Space serves a verified CPU analysis snapshot'],
  },
  scenes,
  candidates: [
    {
      id: 'boundary-111760',
      timestamp: 111.76,
      interruptibility_score: 0.6886,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '1.34s local silence', 'strong visual transition'],
      features: { visual_change: 0.6906, silence_seconds: 1.34, semantic_shift: 0, speech_overlap: false, edge_margin: 111.76 },
    },
    {
      id: 'boundary-310360',
      timestamp: 310.36,
      interruptibility_score: 0.8666,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '6.24s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 0.7306, silence_seconds: 6.243, semantic_shift: 0.8177, speech_overlap: false, edge_margin: 310.36 },
    },
    {
      id: 'boundary-413600',
      timestamp: 413.6,
      interruptibility_score: 0.7497,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '2.11s local silence', 'strong visual transition'],
      features: { visual_change: 0.8602, silence_seconds: 2.108, semantic_shift: 0, speech_overlap: false, edge_margin: 413.6 },
    },
    {
      id: 'boundary-806040',
      timestamp: 806.04,
      interruptibility_score: 0.7234,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '0.60s local silence', 'strong visual transition', 'clear semantic scene change'],
      features: { visual_change: 0.8261, silence_seconds: 0.599, semantic_shift: 0.7815, speech_overlap: false, edge_margin: 590.59 },
    },
    {
      id: 'boundary-940920',
      timestamp: 940.92,
      interruptibility_score: 0.6437,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '0.72s local silence', 'clear semantic scene change'],
      features: { visual_change: 0.5252, silence_seconds: 0.717, semantic_shift: 0.7574, speech_overlap: false, edge_margin: 455.71 },
    },
    {
      id: 'boundary-1001440',
      timestamp: 1001.44,
      interruptibility_score: 0.6547,
      is_safe: true,
      decision: 'Eligible for pacing',
      reasons: ['no detected speech crosses the boundary', '0.87s local silence', 'strong visual transition'],
      features: { visual_change: 0.8536, silence_seconds: 0.873, semantic_shift: 0, speech_overlap: false, edge_margin: 395.19 },
    },
  ],
  breaks: [
    {
      id: 'break-01',
      timestamp: 310.36,
      time_offset: '00:05:10.360',
      score: 0.8666,
      scene_id: 'scene-0003',
      brand: {
        id: 'rannabondhu',
        name: 'RannaBondhu',
        category: 'meal kits',
        tagline: 'Good evenings begin in the kitchen.',
        color: '#D94A3D',
      },
      creative_url: '/media/ads/rannabondhu.mp4',
      duration: 6,
      match_score: 1,
      why: [
        'Food and dinner context aligned with the meal-kit creative',
        '6.24s local silence clears the audio safety gate',
        'Safe transition into the restaurant meal scene',
      ],
      blocked_brands: [],
    },
  ],
  manifest_url: '',
  debug_url: '',
}